<?php
//Starting session if one isnt there
if (session_status() === PHP_SESSION_NONE) {
    session_start();
}

// Making sure only 1 is created
if (empty($_SESSION["ajaxToken"])) {
    // Random_bytes > Md5
    $_SESSION["ajaxToken"] = bin2hex(random_bytes(32));
}

// 3. Save it to a variable so the HTML below can echo it easily
$token = $_SESSION["ajaxToken"];
?>
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <meta name="csrf-token" content="<?php echo htmlspecialchars($token ?? '', ENT_QUOTES, 'UTF-8'); ?>">
    <!--Sending token to js file for security -->
    <link href="Views/css/bootstrap.css" rel="stylesheet">
    <link href="Views/css/bootstrap-theme.css" rel="stylesheet">
    <link href="Views/css/my-style.css" rel="stylesheet">

    <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY="
          crossorigin=""/>
    <script src="https://unpkg.com/leaflet@1.9.4/dist/leaflet.js"
            integrity="sha256-20nQCchB9co0qIjJZRGuk2/Z9VM+kNiyxNV1lvTlZBo="
            crossorigin=""></script>

    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster/dist/MarkerCluster.css" />
    <link rel="stylesheet" href="https://unpkg.com/leaflet.markercluster/dist/MarkerCluster.Default.css" />
    <script src="https://unpkg.com/leaflet.markercluster/dist/leaflet.markercluster.js"></script>

    <title>Pet Watch - <?php echo $view->pageTitle; ?></title>
</head>

<body role="document">

<nav class="navbar navbar-expand-lg navbar-dark bg-dark ">
    <div class="container-fluid" >
        <a class="navbar-brand" href="index.php">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <?php if(!isset($_SESSION['username'])): ?>
                    <li class="nav-item">
                        <a class="nav-link text-light" href="loginController.php">Login</a>
                    </li>
                <?php endif;?>


                <li class="nav-item">
                    <a class="nav-link text-light" href="pets.php">View Pets</a>
                </li>
                <li>
                    <a class="nav-link text-light" href="map.php">Sightings Map</a>
                </li>
                <?php if (isset($_SESSION['userType']) && $_SESSION['userType']=="owner"): ?>
                    <li>
                        <a class="nav-link text-light" href="newPet.php">Add lost pet</a>
                    </li>
                <?php endif;?>


            </ul>
            <?php if(isset($_SESSION['username'])): ?>
                <ul class="navbar-nav me-3">
                    <li class="nav-item">
                        <a class="nav-link text-light" href="logout.php">Logout</a>
                    </li>
                </ul>
            <?php endif ;?>


            <form class="d-flex" action="pets.php" method="get">
                <input class="form-control me-2" type="text" placeholder="Search" aria-label="Search" name="searchItem" onkeyup="liveSearch.handleSearch(this.value)"> <!-- Live search calling function-->
                <button class="btn btn-outline-success" type="submit" name="searchButton" value="submit">Search</button>
            </form>

        </div>
    </div>
</nav>

<div class="container-fluid" style="padding-top: 70px;">

    <div class="row">

        <div class="col-12">
            <h1> </h1>
        </div>
    </div>