<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- Bootstrap core CSS -->
    <link href="Views/css/bootstrap.css" rel="stylesheet">
    <!-- Bootstrap theme -->
    <link href="Views/css/bootstrap-theme.css" rel="stylesheet">
    <link href="Views/css/my-style.css" rel="stylesheet">

    <title>Pet Watch - <?php echo $view->pageTitle; ?></title>
</head>

<body role="document">



<div class="container-fluid p-3">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
        <a class="navbar-brand" href="index.php">Home</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <a class="nav-link text-light" href="loginController.php">Login</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-light" href="passwordController.php">Test</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link text-light" href="pets.php">View Pets</a>
                </li>


            </ul>
            <form class="d-flex">
                <!-- Stick search here so its an end of navbar-->
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="searchBox">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </nav>


    <div class="row">

        <div class="col-12">
            <h1><?php echo $view->pageTitle ?> </h1>
        </div>
    </div>



