<?php require ("template/header.phtml")?>

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-5">
                <form action="loginController.php" method="post">

                    <div class="form-group mb-3">
                        <input type="text" class="form-control" id="username" aria-describedby="username" placeholder="Input Username" name="username">
                    </div>
                    <div class="form-group mb-3">
                        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="password" name="password">
                    </div>
                    <button type="submit" class="btn btn-primary" name="loginButton">Login</button>
                </form>
                <?php if (strlen($view->dbMessage)>0): // I honestly dont remember why I did it this way

                     ?>
                    <div class="alert alert-danger" role="alert">
                        <p><?php echo $view->dbMessage; ?></p>
                    </div>
                <?php endif;?>

            </div>
        </div>
    </div>

<?php require('template/footer.phtml') ?>