<?php require(__DIR__ . "/template/header.phtml");?>
<!--Styling of map-->
    <style>
        #map {
            width: 80%;
            height: 500px;
            margin: 50px auto;
            border: 2px solid #333;
            display: block;
        }
    </style>
<!--Map will be placed here-->
    <div id="map">


    </div>
    <script src= "Views/js/Map.js">

    </script>

<?php require(__DIR__ . "/template/footer.phtml");?>