<?php require(__DIR__ . "/template/header.phtml");?>
<!--Used the "Checkout" bootstrap example to build this page-->
<div class="row g-3 justify-content-center">
    <div class="col-lg-8">

        <h4 class="mb-3">Report a Pet</h4>
        <?php
        if (isset($view->message)){
        ?>

        <div class="alert alert-primary" role="alert">>
            <?php echo $view->message; ?> <a href="pets.php" class="alert-link"> View Pets</a>
        </div>
        <?php
        }
        ?>
        <form action="newPet.php" method="post" enctype="multipart/form-data">
            <input type="hidden" name="user_id" value="<?php echo $_SESSION['user_id']; ?>">


            <div class="row g-3">

                <div class="col-sm-6">
                    <label for="petName" class="form-label">Pet's Name</label>
                    <input
                            type="text"
                            class="form-control"
                            id="petName"
                            name="petName"
                    />
                </div>

                <div class="col-sm-6">
                    <label for="status" class="form-label">Status</label>
                    <select class="form-select" id="status" name="status">

                        <option value="lost">Lost</option>

                    </select>
                </div>

                <div class="col-sm-6">
                    <label for="species" class="form-label">Species</label>
                    <input
                            type="text"
                            class="form-control"
                            id="species"
                            name="species"
                    />
                </div>

                <div class="col-sm-6">
                    <label for="breed" class="form-label">Breed</label>
                    <input
                            type="text"
                            class="form-control"
                            id="breed"
                            name="breed"
                    />
                </div>

                <div class="col-md-6">
                    <label for="colour" class="form-label">Colour</label>
                    <input
                            type="text"
                            class="form-control"
                            id="colour"
                            name="colour"
                    />
                </div>

                <div class="col-md-6">
                    <label for="dateReported" class="form-label">Date Lost/Found</label>
                    <input
                            type="date"
                            class="form-control"
                            id="dateReported"
                            name="dateReported"
                    />
                </div>

                <div class="col-12">
                    <label for="description" class="form-label">Description</label>
                    <textarea
                            class="form-control"
                            id="description"
                            name="description"
                            rows="4"
                    ></textarea>
                </div>

                <div class="col-12">
                    <label for="petPhoto" class="form-label">Photo</label>
                    <input
                            type="file"
                            class="form-control"
                            id="petPhoto"
                            name="petPhoto"
                    />
                </div>

            </div>

            <hr class="my-4" />

            <button class="w-100 btn btn-success btn-lg" type="submit" name="add">
                Add Pet
            </button>
        </form>
    </div>
</div>

<?php require("Views/template/footer.phtml"); ?>
