<?php
require("Views/template/header.phtml"); ?>
<div class="container">
    <div class="container-fluid" >
        <div class ="d-flex justify-content-md-center">
            <div class="text-center">
                <img src="logo.jpg" style="width:50px; height: 50px;">

                <h1 class="px-3">Pet Watch</h1>
                <h2 class ="lead">Helping reunite lost friends</h2>
                <p>Pet Watch is a site where pet owners can log their lost friend.
                    Register as an owner and post a picture and description of your pet
                    and one of our users can submit sightings if they spot what they think can be a friend.
                    If you've seen a pet in your area you can use search our system for what could be that pet and log a sighting
                    possibly reuniting them with their owner.</p>
            </div>



        </div>
    </div>

</div>
<?php require("Views/template/footer.phtml"); ?>