<?php require ("template/header.phtml")?>

    <div class="container mt-5">
        <div class="row justify-content-center">
            <div class="col-md-6 col-lg-5"> <form action="<?php echo $_SERVER['PHP_SELF']; ?>" method="post">
                    <!-- Sets size on different screens
                    takes 6/12 rows on medium screens and 4/12 rows on larger-->
                    <div class="form-group mb-3">
                        <input type="text" class="form-control" id="userID" aria-describedby="userID" placeholder="Input User ID" name="userID">
                    </div>
                    <div class="form-group mb-3">
                        <input type="password" class="form-control" id="exampleInputPassword1" placeholder="password" name="password">
                    </div>
                    <button type="submit" class="btn btn-primary" name="loginButton">Login</button>
                </form>

            </div>
        </div>
    </div>

<?php require('template/footer.phtml') ?>